### ISSUE TITLE
Cannot disable the plugin

### ISSUE THREAD

**Issue by frhou** [strapi-community/strapi-plugin-redis#10]
Hi,

The plugin works well, but on some environments we don't have redis enabled and we cannot disabled it without uninstalling it.
The plugin always fallback to its default configuration (127.0.0.1:6379) and ignore `debug` and `debugIORedis` parameters, it will spam the logs with:

```
[2022-10-19 16:05:10.110] http: GET index.html (4 ms) 200
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[...]
```

Could you please make it so that when no (or specific values like `-1`) are filled in config the plugin is just disabled (like other strapi plugins which don't load when no config is provided).

Thanks !

**Comment by fkukus** [comment]
+1

**Comment by derrickmehaffy** [comment]
Thanks for this, I'll add an enable key here but can you confirm that setting `strapi-plugin-redis: { enabled: false }` doesn't disable it? If not then I can make sure I check it forcefully (this key is typically read by Strapi itself to know if it needs to load the plugin)

**Comment by frhou** [comment]
Thanks for your quick answer !

I tried with this in my `plugin.js` file but I still have the same errors:
```
module.exports = function ({ env }) {
  const config = {
    "strapi-plugins-redis": {
      enabled: false,
    }, 
    redis: {
      enabeld: false,
    },
[...]
```

**Comment by frhou** [comment]
My bad, I did a typo in the conf file (you can see it in my previous message).

With `redis: { enabled: false }` the plugin is indeed disabled in the standard way.
