### ISSUE TITLE
Disable strapi-plugin-redis from running locally?

### ISSUE THREAD

**Issue by cherring07** [strapi-community/strapi-plugin-redis#16]
Is it possible to disable strapi-plugin-redis from running ioredis via config. My local environment does not have redis and I'm seeing lots of logs of it trying to connect. 

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:
```

**Comment by derrickmehaffy** [comment]
You will need to set the redis plugin config option `enabled` to false.

![image](https://user-images.githubusercontent.com/8593673/231882011-4cf43df6-1b5c-466d-bae4-8876514ea3a7.png)

```js
module.exports = {
  redis: {
    enabled: false,
  },
};
```

You can also use env vars:

```js
module.exports = ({ env }) => ({
  redis: {
    enabled: env.bool('REDIS_ENABLED', false),
  },
});
```
