### ISSUE TITLE
Sentinel + Haproxy

### ISSUE THREAD

**Issue by X-Newbie** [strapi-community/strapi-plugin-redis#24]
Hi,

I have 1 sentinel ip, 1 haproxy master ip, 1 haproxy replica ip. I have tried specifying the sentinel ip address. I tried haproxy master + haproxy replica. I tried specifying haproxy master + haproxy replica + sentinel, but none of the options could work. I always get error(All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.) I was using Redis Standalone before and everything worked. Can you help me how to configure caching to work?

**Comment by X-Newbie** [comment]
Example of my config:
`module.exports = {
  redis: {
    config: {
      connections: {
        default: {
          connection: {
            sentinels: [
              { host: 'localhost', port: 26379 },
            ],
            name: 'rendomName',
          },
          settings: {
            debug: false,
          },
        },
      },
    },
  },
};`

**Comment by derrickmehaffy** [comment]
I doubt this is related to my plugin, have you test this with something like redis insights?

**Comment by derrickmehaffy** [comment]
Closing as no response
